services:
  - type: web
    name: keanes-bug-bash
    runtime: static
    buildCommand: pnpm install --frozen-lockfile && pnpm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
